### ISSUE TITLE
3dplot.py Unhandled Exception

### ISSUE THREAD

**Issue by tguard** [QuarkStar/SPH#5]
How do we resolve the 'got unexpected keyword "writer"' exception in 3dplot.py in the i/o branch?
I found <a href="http://fossies.org/dox/matplotlib-1.4.3/classmatplotlib_1_1animation_1_1FuncAnimation.html">this link</a> that explains the relevant class, but I don't see any save() function in it.
Here's my backtrace:

Traceback (most recent call last):
  File "3dplot.py", line 83, in <module>
    main()
  File "3dplot.py", line 72, in main
    ani.save(args.file, writer='imagemagick', fps=args.fps);
TypeError: save() got an unexpected keyword argument 'writer'

**Comment by QuarkStar** [comment]
Do you know if the platform on which you attempted this has the latest version of Matplotlib (or any that support this animation feature)? I remember having problems with ImageMagick but if it doesn’t understand “writer” it may not support that save() function…

Colby

On Mar 17, 2015, at 11:59 AM, Thomas P Gardner <notifications@github.com<mailto:notifications@github.com>> wrote:


How do we resolve the 'got unexpected keyword "writer"' exception in 3dplot.py in the i/o branch?
I found this link<http://fossies.org/dox/matplotlib-1.4.3/classmatplotlib_1_1animation_1_1FuncAnimation.html> that explains the relevant class, but I don't see any save() function in it.
Here's my backtrace:

Traceback (most recent call last):
File "3dplot.py", line 83, in
main()
File "3dplot.py", line 72, in main
ani.save(args.file, writer='imagemagick', fps=args.fps);
TypeError: save() got an unexpected keyword argument 'writer'

**Comment by tguard** [comment]
Found out it was a problem with my matplotlib version. Did you have any problems building from source/pip Dan? Both solutions seem to run into problems for me

**Comment by dan-silver** [comment]
No problems here.  I'm using the latest stable version, 1.4.3
I just uninstalled matplotlib and reinstalled it with `sudo pip install -v matplotlib==1.4.3`

Tested the script with `python 3dplot.py --prefix example --fps=15 --file test.gif --title="testing the title"` and the generated gif is:
![test](https://cloud.githubusercontent.com/assets/1266893/6700606/90b7ca06-ccde-11e4-9ec0-3ef9adb6430b.gif)

Which version of matplot lib are you trying to install?

**Comment by tguard** [comment]
Same one as you, I just keep getting install errors that I can't quite resolve. I'll keep working at it

**Comment by tguard** [comment]
It turns out I didn't have py-dev on my machine, and I didn't fully install the matplotlib dependencies. Still getting errors, but I think I'm almost there

**Comment by dan-silver** [comment]
Does python have something like ruby's gemfiles where we can list all the
dependencies?  So instead of pip installing individual requirements,
everything is handled at once.

**Comment by tguard** [comment]
I think pip will generally do it, but only if its a python-specific library. Does gem list system-level dependencies as well? By system-level I mean libraries like libc or libgtk; non-ruby libraries that the OS can use. For example, I had to `apt-get install libpng` for matplotlib because its not python-specific

**Comment by tguard** [comment]
Got it all fixed up; there is a problem when particles get removed however. An IndexOutOfBounds exception gets thrown if any particles get removed during the simulation (like if they go out of system bounds), so we'll have to take a look at that in 3dplot.py

**Comment by dan-silver** [comment]
Good catch, fixed in 7523077f862ac08a608509bb014a5cdac1fc9323

**Comment by QuarkStar** [comment]
Awesome, thanks for grabbing that. Also, I just realized we forgot to have a meeting..

Sent from my HTC

----- Reply message -----
