### ISSUE TITLE
Modify particle object constructor to optionally accept acceleration, rho, pressure

### ISSUE THREAD

**Issue by dan-silver** [QuarkStar/SPH#6]
The constructor is used when particles are transferred back from the gpu. Without these properties, the calculated values are lost. I think this should be optional to maintain compatibility with the serial version.

**Comment by tguard** [comment]
Would you prefer to send in a numpy array for acceleration or separate x,y,z values?

**Comment by dan-silver** [comment]
Numpy array is fine. Implemented in 2626ab6e609d5e09457b256c103a74a4c84e9cd8
