### ISSUE TITLE
Transfer particle properties to the GPU only at simulation start

### ISSUE THREAD

**Issue by dan-silver** [QuarkStar/SPH#7]
With a6157ac9f4ae9cd8b249a749cacbeccb95696b07 and 07dec37e9bd7227add7f642035d8e2eb2ccdd529, the 3 sim loops (for particle in particles...) have been ported to cuda.  We're still transferring ALL particle data to and from the GPU on each timestep.

The following code needs to be refactored and ported to C.
``` C
	while(t < (maxiter*timestep)):
			if (save*interval) == t:
					fname = "%s-%d.%s" % (ary[0], int(t), ary[1])
					save += 1  # bump save counter
				#	string = "\b%d..." % int(t)     # '\b' prints a backspace character to remove previous space
				#	print string,
					saveParticles(particles, fname)

```

The newly added test 5 from ba4065a989a5c35fbf9890fd3daa3aa1327a791b ensures that we can send particles to the GPU once and call getResultsFromDevice() multiple times.

**Comment by tguard** [comment]
Do you just need the beginning of the while loop ported or do you also need saveParticles() to be ported?

**Comment by dan-silver** [comment]
saveParticles() doesn't need to be ported since file i/o isn't called from the GPU.  I should have time tonight to finish this

**Comment by dan-silver** [comment]
Completed with 4cdd661a9282c4f5a315a7674e97ac295ac4f209
Now on to figuring out why this is 1000x slower than the serial version
