### ISSUE TITLE
GPU version is 100x slower than serial

### ISSUE THREAD

**Issue by dan-silver** [QuarkStar/SPH#8]

**Comment by tguard** [comment]
how many particles are you using? It's possible the extra overhead from the GPU transfer isn't quite worth it for lower particle numbers

**Comment by dan-silver** [comment]
Here's a preview with 10 particles.  It pauses for a few seconds when transferring the data.
(Click to view the video)

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/jGTRR0ipsec/0.jpg)](http://www.youtube.com/watch?v=jGTRR0ipsec)

**Comment by dan-silver** [comment]
Even with just 10 particles, it shouldn't take that long to transfer the data. I'm looking into it.
